<div class="add">
	<h2>Poster un nouveau message :</h2>
 	<form action="messages/<?=$topic->getId()?>" method="post">
		<div class="form-group">
			<label for="contenu">Votre message: </label>
			<textarea autofocus class="form-control" name="contenu" id="contenu"></textarea>
		</div>
		<p class="bg-danger"><?=$error?></p>
		<button name="insert" type="submit" class="btn btn-primary">Nouveau message</button>
	</form>
</div>