<div class="wrapper-droits">
	<div class="row">
		<div class="col-md-offset-1 col-md-2">
			<p><strong><?=htmlentities($message->getAuteur()->getLogin()); ?><strong></p>
		</div>
		<div class="col-md-2">
			<form class="form-inline" action="gestion/<?=$message->getAuteur()->getId()?>" method="post">
				<button name="bannir" type="submit" class="btn btn-danger"><strong>Bannir</strong></button>	
			</form>
		</div>
		<div class="col-md-4">
			<p class="text-success"><?=$_SESSION['success']?></p>
		</div>
	</div>
</div>

