<article class="row">
	<div class="col-xs-4"><a href="home/<?=$topic->getCategory()->getCategory()?>/<?=urlencode($topic->getTitre())?>"><?=htmlentities($topic->getTitre())?></a></div>
	<div class="col-sm-1 col-xs-2">
		<strong><a href="membre/<?=$topic->getIdAuteur()?>"><?=htmlentities($topic->getAuteur()->getLogin())?></a></strong>
	</div>
		<div class="col-sm-2 hidden-xs"><?=htmlentities($topic->count($topic->getId())['COUNT(*)'])?></div>
	<div class="col-sm-2 col-xs-3"><?=htmlentities($topic->getFormatDate())?></div>
	<div class="col-xs-1">
		<a class="btn btn-primary topic-modify" href="modify-topic/<?=$topic->getId()?>"><i class="fa fa-pencil"></i></a>
	</div>
	<div class="col-xs-1">
		<form method="post" action="topic/<?=$topic->getId()?>">
			<button name="remove" class="btn btn-danger topic-remove"type="submit"><i class="fa fa-times"></i></button>
		</form>
	</div>
</article>
<hr />
