<article class="row">
	<div class="col-md-5"><a href="home/<?php echo $topic->getCategory()->getCategory()?>/<?php echo urlencode($topic->getTitre())?>"><?=htmlentities($topic->getTitre())?></a></div>
	<?php
	if (isset($_SESSION['id']))
	{
	?>
		<div class="col-md-1"><a href="membre/<?=$topic->getIdAuteur()?>"><?=htmlentities($topic->getAuteur()->getLogin())?></a></div>
	<?php
	}
	else
	{
		?><div class="col-md-1"><?=htmlentities($topic->getAuteur()->getLogin())?></div>
		<?php
	}
		?>
		<div class="col-md-2"><?=$topic->count($topic->getId())['COUNT(*)']?></div>
	<div class="col-md-2"><?=htmlentities($topic->getFormatDate())?></div>
	<div class="col-md-1">
		<?php require ('./apps/display-modify-topic.php'); ?>
	</div>
	<div class="col-md-1">
		<?php require ('./apps/remove-topic.php'); ?>
	</div>
</article>
<hr />
