<div class="messages-content">
	<hr>
	<div class="row">
		<div class="col-md-2">
			<div class="avatar">
				<img class="thumbnail" src="<?=htmlentities($avatar)?>" alt="">
			</div>
		</div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-5">
					<p><strong><?=htmlentities($login)?></strong></p>
				</div>
				<div class="col-md-5">
					<p><em><?=$date?></em></p>
				</div>
			</div>
			<div class="wrapper-message"><p><?=htmlentities($contenu)?></p></div>
		</div>
	</div>
	<?php require('./apps/modify-message.php'); ?>
	<hr>
</div>