<div class="messages-content">
	<hr>
	<div class="row">
		<div class="col-md-2">
			<div class="avatar">
				<img class="thumbnail" src="./img/avatar1.jpg" alt="">
			</div>
		</div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-5">
					<p><strong>login</strong></p>
				</div>
				<div class="col-md-5">
					<p><em>date</em></p>
				</div>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Perferendis placeat debitis dolore corporis omnis. At odit fugiat nesciunt aspernatur, unde reprehenderit! Impedit iure libero explicabo. A assumenda soluta ex excepturi.</p>
		</div>
	</div>
	<?php require('./apps/modify-message.php'); ?>
	<hr>
</div>