<article class="row">
	<div class="col-xs-4"><a href="home/<?=$topic->getCategory()->getCategory()?>/<?=urlencode($topic->getTitre())?>"><?=htmlentities($topic->getTitre())?></a></div>
	<div class="col-sm-1 col-xs-2">
		<strong><a href="membre/<?=$topic->getIdAuteur()?>"><?=htmlentities($topic->getAuteur()->getLogin())?></a></strong>
	</div>
		<div class="col-sm-2 hidden-xs"><?=htmlentities($topic->count($topic->getId())['COUNT(*)'])?></div>
	<div class="col-sm-2 col-xs-3"><?=htmlentities($topic->getFormatDate())?></div>
</article>
<hr />
