<div class="messages-content">
	<hr>
	<div class="row">
		<div class="col-md-2">
			<div class="avatar">
				<img class="thumbnail" src="<?=htmlentities($user->getAvatar())?>" alt="">
			</div>
		</div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-5">
					<?php require ('./apps/display-login.php'); ?>
				</div>
				<div class="col-md-5">
					<p><em><?=$date?></em></p>
				</div>
			</div>
			<div class="wrapper-message"><p><?=nl2br(htmlentities($message->getContenu()))?></p></div>
		</div>
	</div>
	<?php require('./apps/modify-message.php'); ?>
	<hr>
</div>