<div class="gestion">
	<h1>Interface de gestion</h1>
	<div>
		<h2>Gestion des utilisateurs</h2>
		<div>
			<h3>Gestion des droits</h3>
			<?php require('./apps/droits.php'); ?>
		</div>
		<div>
			<h3>Gestion des utilisateurs signalés</h3>
			<?php require('./apps/ban.php'); ?>
		</div>
	</div>
	<div>
		<h2>Gestion des catégories</h2>
		<div class="categorie">
			<div>
				<h3>Ajouter une catégorie :</h3>
				<form method="post">
					<div class="form-group">
						<input autocomplete="off" autofocus type="text" class="form-control" name="nom">
					</div>
					<p class="bg-danger"><?=$error?></p>
					<button name="create" type="submit" class="btn btn-success">Ajouter</button>
				</form>
			</div>
			<div>
				<h3>Modifier/Supprimer une catégorie :</h3>
				<?php require('./apps/display-categories.php'); ?>
			</div>
		</div>
	</div>
	
</div>
