<div class="gestion">
	<h1>Interface de gestion</h1>
	<div id="gestion-users" class="list-group">
	  	<a href="gestion#gestion-categories" class="list-group-item active">Aller vers "Gestion des catégories"</a>
	</div>
	<div>
		<h2>Gestion des utilisateurs</h2>
		<div>
			<h3>Gestion des droits</h3>
			<?php require('./apps/droits.php'); ?>
		</div>
		<div>
			<h3>Gestion des messages signalés</h3>
			<div class="wrapper-ban">
				<div class="row">
					<div class="col-md-offset-1 col-md-2">
						<p><strong>Utilisateur</strong></p>
					</div>
					<div class="col-md-5">
						<p>Liste des messages signalés</p>
					</div>
					<div class="col-md-4">
						<p>Signalement (cliquer pour réinitialiser)</p>
					</div>
				</div>
				<hr>
				<?php require('./apps/signaled-message.php'); ?>
			</div>
		</div>
	</div>
	<div id="gestion-categories" class="list-group">
	  	<a href="gestion#gestion-users" class="list-group-item active">Aller vers "Gestion des utilisateurs"</a>
	</div>
	<div>
		<h2>Gestion des catégories</h2>
		<div class="categorie">
			<div>
				<h3>Ajouter une catégorie :</h3>
				<form method="post">
					<div class="form-group">
						<input autocomplete="off" type="text" class="form-control" name="nom">
					</div>
					<p class="bg-danger"><?=$error?></p>
					<button name="create" type="submit" class="btn btn-success">Ajouter</button>
				</form>
			</div>
			<div>
				<h3>Modifier/Supprimer une catégorie :</h3>
				<?php require('./apps/display-categories.php'); ?>
			</div>
		</div>
	</div>
	
</div>
