<div class="gestion">
	<h1>Interface de gestion</h1>
	<div>
		<h2>Gestion des catégories</h2>
		<div class="categorie">
			<div>
				<h3>Ajouter une catégorie :</h3>
			</div>
			<div class="row">
				<div class="col-md-offset-2 col-md-4">
					<h4>Boeuf</h4>
				</div>
				<div class="col-md-6">
					<form action="" method="post">
						<button class="btn btn-default" type="submit"><i class="fa fa-plus"></i></button>
						<button class="btn btn-default" type="submit">Button</button>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div>
		<h2>Gestion des utilisateurs</h2>
	</div>
</div>
