<h1>Mes informations</h1>
<p class="bg-danger" role="alert"><?=htmlentities($error)?></p>
<form method="post">
    <fieldset>
        <div class="form-group">
            <label for="login">Login</label>
            <input type="text" class="form-control" id="login" name="login" placeholder="Votre login">
        </div>
        <div class="form-group">
            <label for="email">Adresse email</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Votre mail">
        </div>
        <div class="form-group">
            <label for="oldpassword">Ancien mot de passe</label>
            <input type="password" class="form-control" id="oldpassword" name ="oldpassword" placeholder="Votre mot de passe" value="">
        </div>
        <div class="form-group">
            <label for="password1">Mot de passe</label>
            <input type="password" class="form-control" id="password1" name ="password1" placeholder="Votre mot de passe" value="">
        </div>
        <div class="form-group">
            <label for="password2">Mot de passe (confirmation)</label>
            <input type="password" class="form-control" id="password2" name ="password2" placeholder="Confirmer votre mot de passe" value="">
        </div>
    </fieldset>
    <p class="bg-success" role="alert"><?=htmlentities($success)?></p>
    <button name="validate" type="submit" class="btn btn-default">Enregistrer</button>
</form>