<div class="login">
    <h1>Se connecter</h1>
    <form method="post">
        <div class="form-group">
            <label for="login">Login</label>
            <input name="login" class="form-control" id="login" placeholder="Login">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-default">Envoyer</button>
    </form>
<?php echo $error; 
?>
    <div class="redirect-to-register">
        <p>C'est votre première visite sur notre page et vous n'êtes pas un voleur ? Suivez la </p><i class="fa fa-long-arrow-right"></i><a href="register/"> Pour s'enregistrer</a>
    </div>
</div>