<div class="login">
    <h1>Se connecter</h1>
    <form method="post">
        <div class="form-group">
            <label for="login">Login</label>
            <input autofocus name="login" class="form-control" id="login" placeholder="Login">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
    <p class="bg-danger"><?=$error?></p>
    <div class="redirect-to-register">
        <p>Pas encore inscrit ?
            <a class="btn btn-danger" href="register"> C'est par ici !</a>
        </p>
    </div>
</div>