<h2>Profil de <?=htmlentities($user->getLogin())?></h2>
<div class="row">
	<div class="col-md-2">
		<img src="<?=htmlentities($user->getAvatar())?>" alt="" class="img-thumbnail">
	</div>
	<div class="col-md-10">
		<p><strong>Email</strong> : <?=htmlentities($user->getEmail())?> </p>
		<p><strong>Statut</strong> : <?=htmlentities($statut)?></p>
		<p><strong><?=htmlentities($user->getLogin())?></strong> a publié <?=htmlentities($topic->countMessages($user->getId()))?> messages.</p>
		<p><strong><?=htmlentities($user->getLogin())?></strong> a créé <?=htmlentities($categorie->countTopics($user->getId()))?> topics :</p>
		<div class="row">
			<div class="col-md-offset-1 col-md-3">
				<h4><strong>Catégorie</strong></h4>
			</div>
			<div class="col-md-8">
				<h4>Titre du topic</h4>
			</div>
		</div>
		<?php require ('./apps/profil-topics.php') ?>
	</div>
</div>