<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="home"><img class="logo" src="" alt=""/>La taverne du gros bill</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="home">Home <span class="sr-only">(current)</span></a></li>
        <li class="dropdown">
          <a href="catégories" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Catégories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="categorie/1">Potions</a></li>
            <li><a href="categorie/2">Parchemins</a></li>
            <li><a href="categorie/3">Armes</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="kit">Kit complet</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="promotions">Promotions</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="account" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Mon compte <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="informations">Mes informations</a> </li>
            <li role="separator" class="divider"></li>
            <li><a href="logout"><span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout </a>
          </ul>
        </li>
        <li><a href="cart"><i class="fa fa-cart-arrow-down fa-2x"></i></a>
        </li>
      </ul>

      <form action="search" method="post" class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input class="search" name="search" type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
      </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>