<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="home"><img class="logo" src="" alt=""/>1001 Viandes</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="home">Home</a></li>
                <li class="active"><a href="informations">Mon compte</a></li>
                <li class="active"><a href="logout">Déconnexion</a></li>
            </ul>
            <form method="post" action="search" class="navbar-form navbar-right">
                <div class="form-group">

                  <input name="string" type="text" class="form-control string" placeholder="Recherche par nom de topic">
                </div>
                <button name="search" type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
            </form>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>