<div class="messages-modif">
	<form action="messages/<?=$id?>" method="post">
		<div class="row">
			<div class="col-md-3 col-md-offset-2">
				<button name="signalement" type="submit" class="btn btn-warning">Signaler ce message</button>
			</div>
			<div class="col-md-offset-3 col-md-4">
				<button name="update" type="submit" class="btn btn-success">Modifier</button>
				<button name="delete" type="submit" class="btn btn-danger">Supprimer</button>
			</div>
		</div>
	</form>
</div>