<div class="row">
	<div class="col-md-offset-1 col-md-3">
		<a href="home/<?=htmlentities($topic->getCategory()->getCategory())?>" style="color: #AE3635"><strong><?=htmlentities($topic->getCategory()->getCategory())?></strong></a>
	</div>
	<div class="col-md-8">
		<a href="home/<?=htmlentities($topic->getCategory()->getCategory())?>/<?=urlencode($topic->getTitre())?>"><?=htmlentities($topic->getTitre())?></a>
	</div>
</div>
<hr>