<!DOCTYPE html>
<html lang="fr">
<head>
	<base href="http://localhost/forum/">
	<meta charset="UTF-8">
	<title>1001 Viandes</title>

	<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,700|Roboto:400,500,700,500italic' rel='stylesheet' type='text/css'>
	<!-- Bootstrap -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
	<link rel="stylesheet" href="./styles/style.css" />
	<script type="text/javascript" src="./scripts/jquery-2.1.4.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<!-- Font awesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>

<body>
	<header>
		<h1>1001 viandes</h1>
	</header>
	<?php
		require ('./apps/menu.php');
	?>
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-3">
				<?php
					require ('./apps/tchat.php');
				?>
			</div>
			<div class="col-md-9">
				<?php
					require ('./apps/content.php');
				?>
			</div>
		</div>
	</div>
	
	<script type="text/javascript" src="./scripts/message.js"></script>
</body>
</html>