<div class="full-tchat">
	<div class="tchat">
	<?php
	$j=0;
	while($j<sizeof($messages)){
	?>
		<p>
		<span class="tchat_date">[<?=$messages[$j]->getDate()?>]</span>
		<span class="tchat_auteur"><?=$messages[$j]->getAuteur()->getLogin()?></span> : 
		<span class="tchat_message"><?=$messages[$j]->getMessage()?></span>
		</p>
		
	<?php
		$j++;
	}
	?>
	</div>
	<?php
	if(isset($_SESSION['id'])){ 
	?>
	<form action="tchat" method="POST" id="tchatForm">
		<input type="text" name="message" placeholder="Votre message" id="message" class="form-control">
		<input type="submit" name="submit" value="Ok">
	</form>
	<?php
	}
	?>
</div>