<div class="tchat">
<?php
$j=0;
while($j<sizeof($messages)){
?>
	<p>
	<span class="tchat_date">[<?=$messages[$j]->getDate()?>]</span>
	<span class="tchat_auteur"><?=$messages[$j]->getAuteur()->getLogin()?></span> : 
	<span class="tchat_message"><?=$messages[$j]->getMessage()?></span>
	</p>
	
<?php
	$j++;
}
?>
</div>
<?php
if(isset($_SESSION['id'])){ 
?>
<form method="post">
	<input type="text" class="form-control" placeholder="Votre message">
</form>
<?php 
}
?>