<div class="chemin">
	<p><a href="home/<?=$categoryName?>"><?=htmlentities($categoryName)?></a></p>
</div>
<h2>Nos Topics saignant ou à point !</h2>
<div class="top-header">
	<?php require('./apps/add-topic.php');
	?>
	<!-- pagination  -->
</div>
<div class="row topic-header">
	<div class="col-md-5">Sujet des topics</div>
	<div class="col-md-2">Auteur</div>
	<div class="col-md-1">Messages</div>
	<div class="col-md-2">dernier</div>
	<div class="col-md-2"></div>
</div>
<?php
	require ('./apps/display-topics.php');
?>
