<h1>Topic</h1>
<div class="top-header">
	<button class="btn btn-default" type="submit" value="subject">Nouveau Sujet</button>
	<?php require('./apps/add-topic.php');
	?>
	<!-- pagination  -->
</div>
<div class="row topic-header">
	<div class="col-md-6">Sujet des topics</div>
	<div class="col-md-2">Auteur</div>
	<div class="col-md-2">Messages</div>
	<div class="col-md-2">dernier</div>
</div>
<?php
	require ('./apps/display-topics.php');
?>
