<div class="chemin">
	<p><a href="home/<?=$categoryName?>"><?=htmlentities($categoryName)?></a></p>
</div>
<h2>Nos Topics saignant ou à point !</h2>
<div class="top-header">
	<?php require('./apps/add-topic.php');
	?>
	<!-- pagination  -->
</div>
<div class="row topic-header">
	<div class="col-xs-4">Sujet des topics</div>
	<div class="col-sm-1 col-xs-2">Auteur</div>
	<div class="col-sm-2 hidden-xs">Nombre</div>
	<div class="col-sm-2 col-xs-3">Date</div>
	<div class="col-xs-1"></div>
	<div class="col-xs-1"></div>
</div>
<?php
	require ('./apps/display-topics.php');
?>
